wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.8.35
    code_path: code/training/test.py
    framework: keras
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.6.6
